### ISSUE TITLE
1.12.1 port

### ISSUE THREAD

**Issue by xbony2** [MattCzyr/RealisticTorches#15] opened 2017-09-04 14:18 UTC

**Comment by ChronosWS** [comment] 2018-01-13 23:53
I have submitted a PR which updates this mod to 1.12.2.

**Comment by xbony2** [comment] 2018-01-14 03:25
awesome 👌

**Comment by ChronosWS** [comment] 2018-01-14 03:43
Having one issue though - for some reason it fails when I load the mod using the Twitch launcher in a modpack.

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Realistic Torches (realistictorches)
Caused by: java.lang.NoSuchMethodError: com.chaosthedude.realistictorches.blocks.BlockTorchUnlit.setUnlocalizedName(Ljava/lang/String;)Lnet/minecraft/block/Block;

Not sure why yet.  If anyone happens to know how to resolve this (I have already updated the mappings, made sure I am building with the same forge version as the twitch client launches with, etc.) I'd be interested.  Google isn't quite helping as much as I'd like and I'm still pretty new to building mods for deployment.

**Comment by xbony2** [comment] 2018-01-14 03:46
The reobfuscating is definitely messed out.

**Comment by ChronosWS** [comment] 2018-01-14 03:48
Oh, you think its an obfuscation issue?

**Comment by xbony2** [comment] 2018-01-14 03:51
Yeah. Some part of your code is calling `BlockTorchUnlit#setUnlocalizedName`, but `setUnlocalizedName` should have reobfuscated to `func_somethingobfuscated` when you did `./gradlew build`.

**Comment by ChronosWS** [comment] 2018-01-14 03:52
Ok, fixed that.  Now there's a mod interaction issue I am tracking down.  Almost there!  Funny how all this works in the isolated environment...

**Comment by ChronosWS** [comment] 2018-01-14 04:04
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Realistic Torches (realistictorches)
Caused by: java.lang.NullPointerException
	at codechicken.enderstorage.block.BlockEnderStorage.getLightValue(BlockEnderStorage.java:221)
	at com.chaosthedude.realistictorches.handler.LightSourceHandler.registerLightSources(LightSourceHandler.java:26)

So Block.getLightValue(IBlockState) is deprecated in favor of one which takes a world and position.  During setup, RT is trying to find blocks which passively emit light, while this EnderStorage block only emits light if it is attached to a tile entity, and to figure that out it needs a world and a position.  I can fake a position, but there's no world.  I wonder what the correct way to fix this is...

**Comment by ChronosWS** [comment] 2018-01-14 04:26
Ok, fixed.  Do you want a version of the JAR to buddy-test locally?

**Comment by ChronosWS** [comment] 2018-01-14 04:29
[RealisticTorches-1.12.2-2.1.1.zip](https://github.com/MattCzyr/RealisticTorches/files/1629042/RealisticTorches-1.12.2-2.1.1.zip)

**Comment by xbony2** [comment] 2018-01-14 14:17
If you can get it working it's probably good ^^

**Comment by ChronosWS** [comment] 2018-01-14 18:24
With some luck Matt will get back to this soon and can do an official release.  I see he's a student in college so he's probably been on vacation :)  I can't commit to this repo or do an official release, but I am using it in my personal modpack and it's been working fine.

**Comment by MattCzyr** [comment] 2018-01-15 05:49
I just merged the PR, made a few changes, and submitted version 1.12.2-2.1.1 on CurseForge. Thanks for the help in updating, @ChronosWS , and sorry for the huge delay in actually getting a 1.12 release out.

**Closed as completed by MattCzyr** 2018-01-15 05:50 UTC
