### ISSUE TITLE
Unlit torches have the same light level as lit torches an optifine incompatibility 1.16.4

### ISSUE THREAD

**Issue by Magnetron64** [MattCzyr/RealisticTorches#34] opened 2021-01-11 11:09 UTC
Minecraft 1.16.4 forge + optifine
Current behavior:
![current](https://user-images.githubusercontent.com/74421249/104171461-5dccac00-540b-11eb-98cb-e5768ae235de.png)
Expected behavior:
![expected](https://user-images.githubusercontent.com/74421249/104171473-6329f680-540b-11eb-9578-eaf7dbea4efd.png)
Same thing with dynamic lighting when held in hand the unlit torch emits light.

**Comment by MattCzyr** [comment] 2021-01-11 21:15
Do unlit torches emit light when they are first placed, or only after they are lit then extinguished?

**Comment by jj618** [comment] 2021-01-11 21:18
I have the same issue. 
Realistic torches emit light when they are placed.
I tried to remove shaders and ressource pack but same result.
Minecraft 1.16.4
Forge 35.1.36
Optifine preview_OptiFine_1.16.4_HD_U_G6_pre12

**Comment by Magnetron64** [comment] 2021-01-12 08:03
They emit light after extinguished or placed for the first time (basically always) for me

**Comment by Magnetron64** [comment] 2021-01-12 11:09
They are always lit for me

**Comment by MattCzyr** [comment] 2021-01-12 19:23
Let me know if this beta version fixes the issue:

https://www.dropbox.com/s/i3oc883her98pv9/RealisticTorches-1.16.4-3.1.1-beta.jar?dl=0

**Comment by jj618** [comment] 2021-01-12 20:20
It works for me.
I tested:
- craft realistic torch
- place realistic torch
- light realistic torch with matches
- /weather rain and the torch fade after few seconds

So far so good.
Nice work.

One question: Is it on purpose that the torch can't be taken back after breaking?

**Comment by MattCzyr** [comment] 2021-01-12 20:41
> One question: Is it on purpose that the torch can't be taken back after breaking?

What do you mean?

**Comment by jj618** [comment] 2021-01-12 21:10
> > One question: Is it on purpose that the torch can't be taken back after breaking?
> 
> What do you mean?

I mean that ordinary when you left click on a torch on a wall, the torch break and you can get the torch back but with
the realistic torch, i get nothing. The realistic torch seems to fall through the floor and disappear.

**Comment by jj618** [comment] 2021-01-12 22:37
I noticed something else, with RealisticTorches-1.16.4-3.1.1-beta.jar, lit realistic torches in hand doesn't emit light anymore.

**Comment by MattCzyr** [comment] 2021-01-13 07:01
Both the original issue and the issue with torches not dropping anything should be fixed as of version 3.1.1. Not sure about the handheld lighting issue, but I'll look into it.

**Closed as completed by MattCzyr** 2021-01-13 07:01 UTC
Labels: bug

**Comment by jj618** [comment] 2021-01-13 12:52
I tested RealisticTorches-1.16.4-3.1.1 and everything work has intended:
- torches emit light only when lit
- drop unlit torche when broken
It seems that you can close this issue
Nice work
